# Generated by Django 4.0.6 on 2022-07-31 17:58

from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Employees',
            fields=[
                ('employeenumber', models.IntegerField(db_column='employeeNumber', primary_key=True, serialize=False)),
                ('lastname', models.CharField(db_column='lastName', max_length=50)),
                ('firstname', models.CharField(db_column='firstName', max_length=50)),
                ('extension', models.CharField(max_length=10)),
                ('email', models.CharField(max_length=100)),
                ('jobtitle', models.CharField(db_column='jobTitle', max_length=50)),
            ],
            options={
                'db_table': 'employees',
                'managed': False,
            },
        ),
    ]
