# Generated by Django 4.0.6 on 2022-07-31 18:31

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('GRID_app', '0001_initial'),
    ]

    operations = [
        migrations.CreateModel(
            name='Instadata',
            fields=[
                ('profile_id', models.CharField(max_length=30, primary_key=True, serialize=False)),
                ('image_url', models.CharField(blank=True, db_column='image_URL', max_length=500, null=True)),
                ('score', models.FloatField(blank=True, null=True)),
                ('cat', models.CharField(blank=True, max_length=30, null=True)),
                ('sub_cat', models.CharField(blank=True, max_length=30, null=True)),
                ('attrib', models.CharField(blank=True, max_length=30, null=True)),
            ],
            options={
                'db_table': 'instadata',
                'managed': False,
            },
        ),
        migrations.DeleteModel(
            name='Employees',
        ),
    ]
